name: Docker Image CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0-6'
    
env: 
  REGISTRY_IMAGE: abcdesktopio/libnss-extrausers-rpm

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    strategy:
        fail-fast: false
        matrix:
          # only platform to build, not the image target 
          platform-runs: [ ubuntu-latest, ubuntu-24.04-arm ]
          # this is the target build image
          # debian_bookworm -> debian and bookworm
          # alpine_latest -> alpine and latest
          # distribs: [ debian_bookworm, alpine_latest ]
          distribs: [ rockylinux_8, rockylinux_9, almalinux_8, almalinux_9, almalinux_10 ]
    runs-on: ${{ matrix.platform-runs }} 

    steps:
      - name: Prepare
        id: prepare
        run : |
          # this instance is running on ubuntu-latest or ubuntu-24.04-arm
          # dump values for debug 
          echo matrix.platform-run on ${{ matrix.platform-runs }}
          echo matrix.distribs= ${{ matrix.distribs }}
          # parse distribs debian_bookworm -> DISTRIB=debian and RELEASE=bookworm
          # parse distribs ubuntu_24.04 -> DISTRIB=ubuntu and RELEASE=24.04
          echo ${{ matrix.distribs }} | awk -F "_" '{print "DISTRIB="$1}' >> ${GITHUB_ENV}
          echo ${{ matrix.distribs }} | awk -F "_" '{print "RELEASE="$2}' >> ${GITHUB_ENV}
          # read uname --machine to know the type of cpu amd64 or arm64
          # create env OS_PLATFORM=linux/amd64 and PLATFORM=amd64
          # create env OS_PLATFORM=linux/arm64 and PLATFORM=arm64
          MACHINE=$(uname --machine)
          echo $MACHINE
          if [ $MACHINE = 'x86_64' ]; then 
             echo 'OS_PLATFORM=linux/amd64' >> ${GITHUB_ENV}
             echo 'PLATFORM=amd64' >> ${GITHUB_ENV}
          fi
          if [ $MACHINE = 'aarch64' ]; then 
             echo 'OS_PLATFORM=linux/arm64' >> ${GITHUB_ENV}
             echo 'PLATFORM=arm64' >> ${GITHUB_ENV}
          fi
          
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
           
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
 
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          build-args: |
            BASE_IMAGE=${{ env.DISTRIB }}
            BASE_RELEASE=${{ env.RELEASE }}
          file: Dockerfile
          provenance: false
          platforms: ${{ env.OS_PLATFORM }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ghcr.io/${{ env.REGISTRY_IMAGE }}_${{ env.DISTRIB }}_${{ env.RELEASE }}:${{ env.PLATFORM }}
          outputs: type=image,name-canonical=true,push=true
          # outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Test Docker image
        id: test_image
        uses: docker/build-push-action@v6
        with:
          context: ./testfile/
          push: false
          build-args: |
            TEST_IMAGE=ghcr.io/${{ env.REGISTRY_IMAGE }}_${{ env.DISTRIB }}_${{ env.RELEASE }}
            BASE_IMAGE=${{ env.DISTRIB }}
            BASE_RELEASE=${{ env.PLATFORM }}
          file: ./testfile/Dockerfile.testfile
          platforms: ${{ env.OS_PLATFORM }}

      - uses: shrink/actions-docker-extract@v3
        id: extract-libnss-extrausers-el9
        with:
          image: ghcr.io/${{ env.REGISTRY_IMAGE }}_${{ env.DISTRIB }}_${{ env.RELEASE }}:${{ env.PLATFORM }} 
          path: /output/libnss-extrausers-0.6-1.${{ env.DISTRIB }}.${{ env.RELEASE }}.${{ env.OS_PLATFORM }}.rpm
          destination: target
          
      - name: Upload binaries to release el${{ env.RELEASE }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/libnss-extrausers-0.6-1.${{ env.DISTRIB }}.${{ env.RELEASE }}.${{ env.OS_PLATFORM }}.rpm
          asset_name: libnss-extrausers-0.6-1.${{ env.DISTRIB }}.${{ env.RELEASE }}.${{ env.OS_PLATFORM }}.rpm
          tag: libnss-extrausers-0.6-1
          overwrite: true
          
  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        # distribs: [ debian_bookworm, alpine_latest ]
        distribs: [ rockylinux_8, rockylinux_9, almalinux_8, almalinux_9, almalinux_10 ]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: merge
        uses: int128/docker-manifest-create-action@v2
        with:
          # image format pyos:$distrib_$release
          # for amd64 and arm64
          tags: ghcr.io/${{ env.REGISTRY_IMAGE }}_${{ env.DISTRIB }}
          sources: |
            ghcr.io/${{ env.REGISTRY_IMAGE }}_${{ env.DISTRIB }}:arm64
            ghcr.io/${{ env.REGISTRY_IMAGE }}_${{ env.DISTRIB }}:amd64
