name: Docker Image CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0-6'
    
env: 
  imagename: 'rockylinux'
  imagetag: ${{ github.head_ref || github.ref_name || 'dev' }}
  branch: ${{ github.head_ref || github.ref_name || 'dev' }}
  REGISTRY_IMAGE: abcdesktopio/libnss-extrausers-rpm

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    runs-on: ubuntu-latest

    steps:
          
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
           
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
 
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image rockylinux 8
        id: build_rockylinux_8
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            BASE_IMAGE=rockylinux
            BASE_RELEASE=8
          file: Dockerfile
          platforms: linux/amd64, linux/arm64
          tags: ghcr.io/${{ env.REGISTRY_IMAGE }}_rockylinux:8

      - name: Build and push Docker image rockylinux 9
        id: build_rockylinux_9
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            BASE_IMAGE=rockylinux
            BASE_RELEASE=9
          file: Dockerfile
          platforms: linux/amd64, linux/arm64
          tags: ghcr.io/${{ env.REGISTRY_IMAGE }}_rockylinux:9

      - name: test Docker image rockylinux 8
        id: test_rockylinux_8
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          build-args: |
            TEST_IMAGE=ghcr.io/${{ env.REGISTRY_IMAGE }}_rockylinux
            BASE_IMAGE=rockylinux
            BASE_RELEASE=8
          file: Dockerfile
          platforms: linux/amd64, linux/arm64

      - name: test Docker image rockylinux 9
        id: test_rockylinux_9
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          build-args: |
            TEST_IMAGE=ghcr.io/${{ env.REGISTRY_IMAGE }}_rockylinux
            BASE_IMAGE=rockylinux
            BASE_RELEASE=9
          file: Dockerfile
          platforms: linux/amd64, linux/arm64

      - uses: shrink/actions-docker-extract@v3
        id: extract-libnss-extrausers-el8
        with:
          image: ghcr.io/${{ env.REGISTRY_IMAGE }}_rockylinux:8
          path: /output/libnss-extrausers-0.6-1.el8.x86_64.rpm
          destination: /target/libnss-extrausers-0.6-1.el8.x86_64.rpm

      - uses: shrink/actions-docker-extract@v3
        id: extract-libnss-extrausers-el9
        with:
          image: ghcr.io/${{ env.REGISTRY_IMAGE }}_rockylinux:9
          path: /output/extract-libnss-extrausers-0.6-1.el9.x86_64.rpm
          destination: /target/extract-libnss-extrausers-0.6-1.el9.x86_64.rpm
          
      - name: Upload binaries to release el8
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /target/libnss-extrausers-0.6-1.el8.x86_64.rpm
          asset_name: libnss-extrausers-0.6-1.el8.x86_64.rpm
          tag: 0.6

      - name: Upload binaries to release el9
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /target/libnss-extrausers-0.6-1.el9.x86_64.rpm
          asset_name: libnss-extrausers-0.6-1.el9.x86_64.rpm
          tag: 0.6
 

 
